namespace Bible.Data.Models
{
    public enum BibleBookIndex
    {
        Genesis = 0,
        Exodus = 1,
        Leviticus = 2,
        Numbers = 3,
        Deuteronomy = 4,
        Joshua = 5,
        Judges = 6,
        Ruth = 7,
        FirstSamuel = 8,
        SecondSamuel = 9,
        FirstKings = 10,
        SecondKings = 11,
        FirstChronicles = 12,
        SecondChronicles = 13,
        Ezra = 14,
        Nehemiah = 15,
        Esther = 16,
        Job = 17,
        Psalms = 18,
        Proverbs = 19,
        Ecclesiastes = 20,
        SongOfSolomon = 21,
        Isaiah = 22,
        Jeremiah = 23,
        Lamentations = 24,
        Ezekiel = 25,
        Daniel = 26,
        Hosea = 27,
        Joel = 28,
        Amos = 29,
        Obadiah = 30,
        Jonah = 31,
        Micah = 32,
        Nahum = 33,
        Habakkuk = 34,
        Zephaniah = 35,
        Haggai = 36,
        Zechariah = 37,
        Malachi = 38,
        Matthew = 39,
        Mark = 40,
        Luke = 41,
        John = 42,
        Acts = 43,
        Romans = 44,
        FirstCorinthians = 45,
        SecondCorinthians = 46,
        Galatians = 47,
        Ephesians = 48,
        Philippians = 49,
        Colossians = 50,
        FirstThessalonians = 51,
        SecondThessalonians = 52,
        FirstTimothy = 53,
        SecondTimothy = 54,
        Titus = 55,
        Philemon = 56,
        Hebrews = 57,
        James = 58,
        FirstPeter = 59,
        SecondPeter = 60,
        FirstJohn = 61,
        SecondJohn = 62,
        ThirdJohn = 63,
        Jude = 64,
        Revelation = 65
    }

    public enum BibleBookNumber
    {
        First = 1,
        Second = 2,
        Third = 3
    }
}