namespace Bible.Data.Models
{
    internal class BibleBookLookup
    {
        public static readonly Dictionary<BibleBookIndex, string> BibleBookNames = new()
        {
            { BibleBookIndex.Genesis, "Genesis" },
            { BibleBookIndex.Exodus, "Exodus" },
            { BibleBookIndex.Leviticus, "Leviticus" },
            { BibleBookIndex.Numbers, "Numbers" },
            { BibleBookIndex.Deuteronomy, "Deuteronomy" },
            { BibleBookIndex.Joshua, "Joshua" },
            { BibleBookIndex.Judges, "Judges" },
            { BibleBookIndex.Ruth, "Ruth" },
            { BibleBookIndex.FirstSamuel, "1 Samuel" },
            { BibleBookIndex.SecondSamuel, "2 Samuel" },
            { BibleBookIndex.FirstKings, "1 Kings" },
            { BibleBookIndex.SecondKings, "2 Kings" },
            { BibleBookIndex.FirstChronicles, "1 Chronicles" },
            { BibleBookIndex.SecondChronicles, "2 Chronicles" },
            { BibleBookIndex.Ezra, "Ezra" },
            { BibleBookIndex.Nehemiah, "Nehemiah" },
            { BibleBookIndex.Esther, "Esther" },
            { BibleBookIndex.Job, "Job" },
            { BibleBookIndex.Psalms, "Psalms" },
            { BibleBookIndex.Proverbs, "Proverbs" },
            { BibleBookIndex.Ecclesiastes, "Ecclesiastes" },
            { BibleBookIndex.SongOfSolomon, "Song of Solomon" },
            { BibleBookIndex.Isaiah, "Isaiah" },
            { BibleBookIndex.Jeremiah, "Jeremiah" },
            { BibleBookIndex.Lamentations, "Lamentations" },
            { BibleBookIndex.Ezekiel, "Ezekiel" },
            { BibleBookIndex.Daniel, "Daniel" },
            { BibleBookIndex.Hosea, "Hosea" },
            { BibleBookIndex.Joel, "Joel" },
            { BibleBookIndex.Amos, "Amos" },
            { BibleBookIndex.Obadiah, "Obadiah" },
            { BibleBookIndex.Jonah, "Jonah" },
            { BibleBookIndex.Micah, "Micah" },
            { BibleBookIndex.Nahum, "Nahum" },
            { BibleBookIndex.Habakkuk, "Habakkuk" },
            { BibleBookIndex.Zephaniah, "Zephaniah" },
            { BibleBookIndex.Haggai, "Haggai" },
            { BibleBookIndex.Zechariah, "Zechariah" },
            { BibleBookIndex.Malachi, "Malachi" },
            { BibleBookIndex.Matthew, "Matthew" },
            { BibleBookIndex.Mark, "Mark" },
            { BibleBookIndex.Luke, "Luke" },
            { BibleBookIndex.John, "John" },
            { BibleBookIndex.Acts, "Acts" },
            { BibleBookIndex.Romans, "Romans" },
            { BibleBookIndex.FirstCorinthians, "1 Corinthians" },
            { BibleBookIndex.SecondCorinthians, "2 Corinthians" },
            { BibleBookIndex.Galatians, "Galatians" },
            { BibleBookIndex.Ephesians, "Ephesians" },
            { BibleBookIndex.Philippians, "Philippians" },
            { BibleBookIndex.Colossians, "Colossians" },
            { BibleBookIndex.FirstThessalonians, "1 Thessalonians" },
            { BibleBookIndex.SecondThessalonians, "2 Thessalonians" },
            { BibleBookIndex.FirstTimothy, "1 Timothy" },
            { BibleBookIndex.SecondTimothy, "2 Timothy" },
            { BibleBookIndex.Titus, "Titus" },
            { BibleBookIndex.Philemon, "Philemon" },
            { BibleBookIndex.Hebrews, "Hebrews" },
            { BibleBookIndex.James, "James" },
            { BibleBookIndex.FirstPeter, "1 Peter" },
            { BibleBookIndex.SecondPeter, "2 Peter" },
            { BibleBookIndex.FirstJohn, "1 John" },
            { BibleBookIndex.SecondJohn, "2 John" },
            { BibleBookIndex.ThirdJohn, "3 John" },
            { BibleBookIndex.Jude, "Jude" },
            { BibleBookIndex.Revelation, "Revelation" }
        };
    }
}
