# name: Deploy

on:
  workflow_call:
    inputs:
      artifact_name:
        description: 'Artifact name'
        default: 'github-pages'
        type: string
    outputs:
      page_url:
        description: 'The webpage URL'
        value: ${{ jobs.deploy_website.outputs.page_url }}

jobs:
  deploy_website:
    name: 🚀 GitHub Page

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: ${{ inputs.artifact_name }}
      url: ${{ steps.deployment.outputs.page_url }}

    outputs:
      page_url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/deploy-pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action